name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        turn: [0, 1, 2, 3, 4, 5 ,6, 7, 8, 9, 10]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies ${{ matrix.turn }}
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Server
      run: npx playwright run-server --port 8090 &
      env:
        DEBUG: pw:browser*
        DEBUG_FILE: log/server.log

    - name: Run Playwright tests
      run: npx playwright test
      env:
        DEBUG: pw:browser*
        DEBUG_FILE: log/debug.log
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: log
        path: log/
        retention-days: 30
